name: Mistake Notifier

on:
  workflow_run:
    workflows: [Mistake Checker]
    types:
      - completed

jobs:
  notify:
    name: Notify of mistakes
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      issues: write

    steps:
      - name: Download mistake checker results
        uses: actions/download-artifact@v3
        with:
          name: mistakes
          path: ${{ github.workspace }}/mistakes.json

      - name: Output detected mistakes if any
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const mistakes_json = JSON.parse(fs.readFileSync('./mistakes.json'))

            let message = "";

            if (mistakes_json.length > 0) {
              message += 'Thank you for contributing!\n\n';
              message += 'To keep translations error-free, we check them for mistakes. The files you changed seem to contain some, no worries though, they can be fixed! ';
              message += `See helpful info below:\n\`\`\`diff\n`;
              message += "===================================================================\n";

              mistakes_json.mistakes.forEach((mistake) => {
                message += `@@ Line: ${mistake.line} @@\n`;

                switch (mistake.mistake_type) {
                  case "invalid_s":
                    message += '--- Missing %s\n';
                    message += `+ msgid "${mistake.id}"\n`;
                    message += `- msgstr "${mistake.str}"\n`;
                    break;
                  case "invalid_color":
                    message += '!!! Missing colors\n';
                    message += `+ msgid "${mistake.id}"\n`;
                    message += `- msgstr "${mistake.str}"\n`;
                    break;
                }

                message += '***************\n'
              })
            }

            message += "===================================================================\n```";

            if (message !== "") {
              github.rest.issues.createComment({
                issue_number: mistakes_json.pr_id,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: message
              });
            }
