name: Mistake Notifier

on:
  workflow_run:
    workflows: [Mistake Checker]
    types:
      - completed

jobs:
  notify:
    name: Notify of mistakes
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      issues: write

    steps:
      - name: Download mistake checker results
        uses: actions/github-script@v6
        with:
          script: |
            let allArtifacts = await github.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: ${{ github.event.workflow_run.id }},
            });
            
            let matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "mistakes"
            })[0];
            
            let download = await github.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            
            let fs = require('fs');
            fs.writeFileSync('${{ github.workspace }}/pr.zip', Buffer.from(download.data));
            
      - run: unzip pr.zip

      - name: Output detected mistakes if any
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const mistakes_json = JSON.parse(fs.readFileSync('./mistakes.json'))

            let message = "";

            if (mistakes_json.length > 0) {
              message += 'Thank you for contributing!\n\n';
              message += 'To keep translations error-free, we check them for mistakes. The files you changed seem to contain some, no worries though, they can be fixed! ';
              message += `See helpful info below:\n\`\`\`diff\n`;
              message += "===================================================================\n";

              mistakes_json.mistakes.forEach((mistake) => {
                message += `@@ Line: ${mistake.line} @@\n`;

                switch (mistake.mistake_type) {
                  case "invalid_s":
                    message += '--- Missing %s\n';
                    message += `+ msgid "${mistake.id}"\n`;
                    message += `- msgstr "${mistake.str}"\n`;
                    break;
                  case "invalid_color":
                    message += '!!! Missing colors\n';
                    message += `+ msgid "${mistake.id}"\n`;
                    message += `- msgstr "${mistake.str}"\n`;
                    break;
                }

                message += '***************\n'
              })
            }

            message += "===================================================================\n```";

            if (message !== "") {
              github.rest.issues.createComment({
                issue_number: mistakes_json.pr_id,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: message
              });
            }
